---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: charansait372/shopping-cart:latestv2
          imagePullPolicy: Always
          ports:
            - containerPort: 8070

---
apiVersion: v1
kind: Service
metadata:
  name: boardgame
spec:
  selector:
    app: boardgame
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
  type: LoadBalancer
